### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by brw31415** [bignimbus/extended-javascript-console#43]
hi, i just installed this to chrome on my chromebook as an extenion from the chromestore, but when i try console.out('joe'); it says console.out is undefined. thanks

**Comment by bignimbus** [comment]
Are all URLs affected?  The extension uses an AJAX request and some sites block these requests.  I should probably just hardcode the JS into the next release.  Any more information that could help pin the bug down would be very helpful.

**Comment by brw31415** [comment]
i was using it without a server, which i guess is necessary for ajax magic,
but through the server it's fine. tnx.

**Comment by bignimbus** [comment]
Glad to hear it works fine over a good connection.  I am looking into better ways to implement this.
